const ComponentData = [
  {
    name: "LED Light Bulb",
    minWatts: 5,
    maxWatts: 100,
    step: 1,
  },
  {
    name: "Ceiling Fan",
    minWatts: 35,
    maxWatts: 200,
    step: 5,
  },
  {
    name: "Mobile Phone Charger",
    minWatts: 5,
    maxWatts: 300,
    step: 1,
  },
  {
    name: "Electric Motor",
    minWatts: 500,
    maxWatts: 5000,
    step: 100,
  },
  {
    name:"Air Cooler",
    minWatts: 100,
    maxWatts: 1000,
    step: 10,
  },
  {
    name:"Submersible Pump",
    minWatts: 500,
    maxWatts: 5000,
    step: 100,
  },
  {
    name: "Refrigerator",
    minWatts: 500,
    maxWatts: 5000,
    step: 50,
  },
  {
    name: "Washing Machine",
    minWatts: 500,
    maxWatts: 3000,
    step: 50,
  },
  {
    name: "Air Conditioner (Window) AC",
    minWatts: 1000,
    maxWatts: 5000,
    step: 200,
  },
  {
    name: "Air Conditioner (Split) AC",
    minWatts: 1000,
    maxWatts: 6000,
    step: 200,
  },
  {
    name: "Clothes Iron",
    minWatts: 300,
    maxWatts: 2000,
    step: 50,
  },
  {
    name: "Television",
    minWatts: 50,
    maxWatts: 500,
    step: 10,
  },
  {
    name: "Electric Heater",
    minWatts: 1000,
    maxWatts: 5000,
    step: 200,
  },
  {
    name: "Microwave Oven",
    minWatts: 600,
    maxWatts: 1200,
    step: 50,
  },
  {
    name: "Coffee Maker",
    minWatts: 800,
    maxWatts: 1200,
    step: 50,
  },
  {
    name: "Hair Dryer",
    minWatts: 1000,
    maxWatts: 2000,
    step: 100,
  },
  {
    name: "Laptop Charger",
    minWatts: 20,
    maxWatts: 500,
    step: 5,
  },
  {
    name: "Desktop Computer",
    minWatts: 100,
    maxWatts: 2000,
    step: 20,
  },
  {
    name: "Dishwasher",
    minWatts: 1200,
    maxWatts: 1800,
    step: 100,
  },
  {
    name: "Toaster",
    minWatts: 500,
    maxWatts: 1500,
    step: 50,
  },
  {
    name: "Electric Kettle",
    minWatts: 1200,
    maxWatts: 2000,
    step: 100,
  },
  {
    name: "Blender",
    minWatts: 300,
    maxWatts: 1000,
    step: 50,
  },
  {
    name: "Vacuum Cleaner",
    minWatts: 500,
    maxWatts: 2000,
    step: 100,
  },
  {
    name: "Electric Oven",
    minWatts: 1000,
    maxWatts: 5000,
    step: 200,
  },
  {
    name: "Water Geyser",
    minWatts: 1000,
    maxWatts: 5000,
    step: 200,
  },
  {
    name: "Ceiling Light Fixture",
    minWatts: 5,
    maxWatts: 100,
    step: 5,
  },
  {
    name: "Floor Lamp",
    minWatts: 20,
    maxWatts: 150,
    step: 10,
  },
  {
    name: "Desk Lamp",
    minWatts: 10,
    maxWatts: 60,
    step: 5,
  },
  {
    name: "Table Fan",
    minWatts: 20,
    maxWatts: 500,
    step: 5,
  },
  {
    name: "Air Purifier",
    minWatts: 500,
    maxWatts: 3000,
    step: 5,
  },
  {
    name: "Heated Blanket",
    minWatts: 50,
    maxWatts: 200,
    step: 10,
  },
  {
    name: "Electric Blanket",
    minWatts: 50,
    maxWatts: 200,
    step: 10,
  },
  {
    name: "Food Processor",
    minWatts: 200,
    maxWatts: 1000,
    step: 50,
  },
  {
    name: "Rice Cooker",
    minWatts: 300,
    maxWatts: 1000,
    step: 50,
  },
  {
    name: "Juicer",
    minWatts: 300,
    maxWatts: 1500,
    step: 50,
  },
  {
    name: "Hand Mixer",
    minWatts: 100,
    maxWatts: 400,
    step: 25,
  },
  {
    name: "Electric Shaver",
    minWatts: 5,
    maxWatts: 50,
    step: 1,
  },
  {
    name: "Electric Toothbrush Charger",
    minWatts: 1,
    maxWatts: 5,
    step: 1,
  },
  {
    name: "Electric Scooter Charger",
    minWatts: 50,
    maxWatts: 1000,
    step: 10,
  },
  {
    name: "Electric Bicycle Charger",
    minWatts: 50,
    maxWatts: 1000,
    step: 10,
  },
  {
    name: "Electric Skateboard Charger",
    minWatts: 50,
    maxWatts: 1000,
    step: 10,
  },
  {
    name: "Gaming Console Charger",
    minWatts: 50,
    maxWatts: 150,
    step: 10,
  },
  {
    name: "Digital Camera Charger",
    minWatts: 5,
    maxWatts: 20,
    step: 1,
  },
  {
    name: "Portable Speaker Charger",
    minWatts: 5,
    maxWatts: 20,
    step: 1,
  },
  {
    name: "Smartwatch Charger",
    minWatts: 1,
    maxWatts: 50,
    step: 1,
  },
  {
    name: "Headphone Charger",
    minWatts: 1,
    maxWatts: 50,
    step: 1,
  },
  {
    name: "Electric Guitar Amplifier",
    minWatts: 20,
    maxWatts: 200,
    step: 10,
  },
  {
    name: "Electric Bass Amplifier",
    minWatts: 20,
    maxWatts: 2000,
    step: 10,
  },
  {
    name: "Home Theater System",
    minWatts: 100,
    maxWatts: 2500,
    step: 20,
  },
  {
    name: "Projector",
    minWatts: 100,
    maxWatts: 1500,
    step: 50,
  },
  {
    name: "Gaming PC",
    minWatts: 300,
    maxWatts: 1000,
    step: 50,
  },
  {
    name: "Electric Skateboard",
    minWatts: 300,
    maxWatts: 1000,
    step: 50,
  },
  {
    name: "Hoverboard",
    minWatts: 300,
    maxWatts: 1000,
    step: 50,
  },
  {
    name: "Electric Wheelchair",
    minWatts: 200,
    maxWatts: 500,
    step: 20,
  },
  {
    name: "Electric Scooter",
    minWatts: 200,
    maxWatts: 500,
    step: 20,
  },
  {
    name: "Electric Bike",
    minWatts: 200,
    maxWatts: 500,
    step: 20,
  },
  {
    name: "Electric Lawn Mower",
    minWatts: 500,
    maxWatts: 1500,
    step: 50,
  },
];

export default ComponentData;

