const ComponentData = [
  {
    id: 1,
    name: "LED Light Bulb",
    minWatts: 5,
    maxWatts: 100,
    step: 1,
  },
  {
    id: 2,
    name: "Ceiling Fan",
    minWatts: 35,
    maxWatts: 200,
    step: 5,
  },
  {
    id: 3,
    name: "Mobile Phone Charger",
    minWatts: 5,
    maxWatts: 300,
    step: 1,
  },
  {
    id: 4,
    name: "Electric Motor",
    minWatts: 500,
    maxWatts: 5000,
    step: 100,
  },
  {
    id: 5,
    name: "Air Cooler",
    minWatts: 100,
    maxWatts: 1000,
    step: 10,
  },
  {
    id: 6,
    name: "Submersible Pump",
    minWatts: 500,
    maxWatts: 5000,
    step: 100,
  },
  {
    id: 7,
    name: "Refrigerator",
    minWatts: 500,
    maxWatts: 5000,
    step: 50,
  },
  {
    id: 8,
    name: "Washing Machine",
    minWatts: 500,
    maxWatts: 3000,
    step: 50,
  },
  {
    id: 9,
    name: "Air Conditioner (Window) AC",
    minWatts: 1000,
    maxWatts: 5000,
    step: 200,
  },
  {
    id: 10,
    name: "Air Conditioner (Split) AC",
    minWatts: 1000,
    maxWatts: 6000,
    step: 200,
  },
  {
    id: 11,
    name: "Clothes Iron",
    minWatts: 300,
    maxWatts: 2000,
    step: 50,
  },
  {
    id: 12,
    name: "Television",
    minWatts: 50,
    maxWatts: 500,
    step: 10,
  },
  {
    id: 13,
    name: "Electric Heater",
    minWatts: 1000,
    maxWatts: 5000,
    step: 200,
  },
  {
    id: 14,
    name: "Microwave Oven",
    minWatts: 600,
    maxWatts: 1200,
    step: 50,
  },
  {
    id: 15,
    name: "Coffee Maker",
    minWatts: 800,
    maxWatts: 1200,
    step: 50,
  },
  {
    id: 16,
    name: "Hair Dryer",
    minWatts: 1000,
    maxWatts: 2000,
    step: 100,
  },
  {
    id: 17,
    name: "Laptop Charger",
    minWatts: 20,
    maxWatts: 500,
    step: 5,
  },
  {
    id: 18,
    name: "Desktop Computer",
    minWatts: 100,
    maxWatts: 2000,
    step: 20,
  },
  {
    id: 19,
    name: "Dishwasher",
    minWatts: 1200,
    maxWatts: 1800,
    step: 100,
  },
  {
    id: 20,
    name: "Toaster",
    minWatts: 500,
    maxWatts: 1500,
    step: 50,
  },
  {
    id: 21,
    name: "Electric Kettle",
    minWatts: 1200,
    maxWatts: 2000,
    step: 100,
  },
  {
    id: 22,
    name: "Blender",
    minWatts: 300,
    maxWatts: 1000,
    step: 50,
  },
  {
    id: 23,
    name: "Vacuum Cleaner",
    minWatts: 500,
    maxWatts: 2000,
    step: 100,
  },
  {
    id: 24,
    name: "Electric Oven",
    minWatts: 1000,
    maxWatts: 5000,
    step: 200,
  },
  {
    id: 25,
    name: "Water Geyser",
    minWatts: 1000,
    maxWatts: 5000,
    step: 200,
  },
  {
    id: 26,
    name: "Ceiling Light Fixture",
    minWatts: 5,
    maxWatts: 100,
    step: 5,
  },
  {
    id: 27,
    name: "Floor Lamp",
    minWatts: 20,
    maxWatts: 150,
    step: 10,
  },
  {
    id: 28,
    name: "Desk Lamp",
    minWatts: 10,
    maxWatts: 60,
    step: 5,
  },
  {
    id: 29,
    name: "Table Fan",
    minWatts: 20,
    maxWatts: 500,
    step: 5,
  },
  {
    id: 30,
    name: "Air Purifier",
    minWatts: 500,
    maxWatts: 3000,
    step: 5,
  },
  {
    id: 31,
    name: "Heated Blanket",
    minWatts: 50,
    maxWatts: 200,
    step: 10,
  },
  {
    id: 32,
    name: "Electric Blanket",
    minWatts: 50,
    maxWatts: 200,
    step: 10,
  },
  {
    id: 33,
    name: "Food Processor",
    minWatts: 200,
    maxWatts: 1000,
    step: 50,
  },
  {
    id: 34,
    name: "Rice Cooker",
    minWatts: 300,
    maxWatts: 1000,
    step: 50,
  },
  {
    id: 35,
    name: "Juicer",
    minWatts: 300,
    maxWatts: 1500,
    step: 50,
  },
  {
    id: 36,
    name: "Hand Mixer",
    minWatts: 100,
    maxWatts: 400,
    step: 25,
  },
  {
    id: 37,
    name: "Electric Shaver",
    minWatts: 5,
    maxWatts: 50,
    step: 1,
  },
  {
    id: 38,
    name: "Electric Toothbrush Charger",
    minWatts: 1,
    maxWatts: 5,
    step: 1,
  },
  {
    id: 39,
    name: "Electric Scooter Charger",
    minWatts: 50,
    maxWatts: 1000,
    step: 10,
  },
  {
    id: 40,
    name: "Electric Bicycle Charger",
    minWatts: 50,
    maxWatts: 1000,
    step: 10,
  },
  {
    id: 41,
    name: "Electric Skateboard Charger",
    minWatts: 50,
    maxWatts: 1000,
    step: 10,
  },
  {
    id: 42,
    name: "Gaming Console Charger",
    minWatts: 50,
    maxWatts: 150,
    step: 10,
  },
  {
    id: 43,
    name: "Digital Camera Charger",
    minWatts: 5,
    maxWatts: 20,
    step: 1,
  },
  {
    id: 44,
    name: "Portable Speaker Charger",
    minWatts: 5,
    maxWatts: 20,
    step: 1,
  },
  {
    id: 45,
    name: "Smartwatch Charger",
    minWatts: 1,
    maxWatts: 50,
    step: 1,
  },
  {
    id: 46,
    name: "Headphone Charger",
    minWatts: 1,
    maxWatts: 50,
    step: 1,
  },
  {
    id: 47,
    name: "Electric Guitar Amplifier",
    minWatts: 20,
    maxWatts: 200,
    step: 10,
  },
  {
    id: 48,
    name: "Electric Bass Amplifier",
    minWatts: 20,
    maxWatts: 2000,
    step: 10,
  },
  {
    id: 49,
    name: "Home Theater System",
    minWatts: 100,
    maxWatts: 2500,
    step: 20,
  },
  {
    id: 50,
    name: "Projector",
    minWatts: 100,
    maxWatts: 1500,
    step: 50,
  },
  {
    id: 51,
    name: "Gaming PC",
    minWatts: 300,
    maxWatts: 1000,
    step: 50,
  },
  {
    id:52,
    name: "Electric Skateboard",
    minWatts: 300,
    maxWatts: 1000,
    step: 50,
  },
  {
    id:53,
    name: "Hoverboard",
    minWatts: 300,
    maxWatts: 1000,
    step: 50,
  },
  {
    id:54,
    name: "Electric Wheelchair",
    minWatts: 200,
    maxWatts: 500,
    step: 20,
  },
  {
    id:55,
    name: "Electric Scooter",
    minWatts: 200,
    maxWatts: 500,
    step: 20,
  },
  {
    id:56,
    name: "Electric Bike",
    minWatts: 200,
    maxWatts: 500,
    step: 20,
  },
  {
    id:57,
    name: "Electric Lawn Mower",
    minWatts: 500,
    maxWatts: 1500,
    step: 50,
  },
];

export default ComponentData;

