const ComponentData = [
  {
    name: "LED Light Bulb",
    imageUrl: "https://example.com/led_light_bulb.jpg",
    minWatts: 5,
    maxWatts: 50,
    step: 1,
  },
  {
    name: "Ceiling Fan",
    imageUrl: "https://example.com/ceiling_fan.jpg",
    minWatts: 40,
    maxWatts: 300,
    step: 5,
  },
  {
    name: "Mobile Phone Charger",
    imageUrl: "https://example.com/mobile_phone_charger.jpg",
    minWatts: 5,
    maxWatts: 100,
    step: 1,
  },
  {
    name: "Electric Motor",
    imageUrl: "https://example.com/electric_motor.jpg",
    minWatts: 500,
    maxWatts: 5000,
    step: 100,
  },
  {
    name: "Refrigerator",
    imageUrl: "https://example.com/refrigerator.jpg",
    minWatts: 100,
    maxWatts: 1500,
    step: 50,
  },
  {
    name: "Washing Machine",
    imageUrl: "https://example.com/washing_machine.jpg",
    minWatts: 500,
    maxWatts: 1500,
    step: 50,
  },
  {
    name: "Air Conditioner (Window)",
    imageUrl: "https://example.com/window_air_conditioner.jpg",
    minWatts: 1000,
    maxWatts: 5000,
    step: 200,
  },
  {
    name: "Air Conditioner (Split)",
    imageUrl: "https://example.com/split_air_conditioner.jpg",
    minWatts: 1000,
    maxWatts: 6000,
    step: 200,
  },
  {
    name: "Clothes Iron",
    imageUrl: "https://example.com/clothes_iron.jpg",
    minWatts: 300,
    maxWatts: 2000,
    step: 50,
  },
  {
    name: "Television",
    imageUrl: "https://example.com/television.jpg",
    minWatts: 50,
    maxWatts: 500,
    step: 10,
  },
  {
    name: "Electric Heater",
    imageUrl: "https://example.com/electric_heater.jpg",
    minWatts: 1000,
    maxWatts: 5000,
    step: 200,
  },
  {
    name: "Microwave Oven",
    imageUrl: "https://example.com/microwave_oven.jpg",
    minWatts: 600,
    maxWatts: 1200,
    step: 50,
  },
  {
    name: "Coffee Maker",
    imageUrl: "https://example.com/coffee_maker.jpg",
    minWatts: 800,
    maxWatts: 1200,
    step: 50,
  },
  {
    name: "Hair Dryer",
    imageUrl: "https://example.com/hair_dryer.jpg",
    minWatts: 1000,
    maxWatts: 2000,
    step: 100,
  },
  {
    name: "Laptop Charger",
    imageUrl: "https://example.com/laptop.jpg",
    minWatts: 20,
    maxWatts: 200,
    step: 5,
  },
  {
    name: "Desktop Computer",
    imageUrl: "https://example.com/desktop_computer.jpg",
    minWatts: 100,
    maxWatts: 500,
    step: 20,
  },
  {
    name: "Dishwasher",
    imageUrl: "https://example.com/dishwasher.jpg",
    minWatts: 1200,
    maxWatts: 1800,
    step: 100,
  },
  {
    name: "Toaster",
    imageUrl: "https://example.com/toaster.jpg",
    minWatts: 800,
    maxWatts: 1500,
    step: 50,
  },
  {
    name: "Electric Kettle",
    imageUrl: "https://example.com/electric_kettle.jpg",
    minWatts: 1200,
    maxWatts: 2000,
    step: 100,
  },
  {
    name: "Blender",
    imageUrl: "https://example.com/blender.jpg",
    minWatts: 300,
    maxWatts: 1000,
    step: 50,
  },
  {
    name: "Vacuum Cleaner",
    imageUrl: "https://example.com/vacuum_cleaner.jpg",
    minWatts: 500,
    maxWatts: 2000,
    step: 100,
  },
  {
    name: "Electric Oven",
    imageUrl: "https://example.com/electric_oven.jpg",
    minWatts: 1000,
    maxWatts: 5000,
    step: 200,
  },
  {
    name: "Water Geyser",
    imageUrl: "https://example.com/electric_oven.jpg",
    minWatts: 1000,
    maxWatts: 5000,
    step: 200,
  },
  {
    name: "Ceiling Light Fixture",
    imageUrl: "https://example.com/ceiling_light_fixture.jpg",
    minWatts: 10,
    maxWatts: 100,
    step: 5,
  },
  {
    name: "Floor Lamp",
    imageUrl: "https://example.com/floor_lamp.jpg",
    minWatts: 20,
    maxWatts: 150,
    step: 10,
  },
  {
    name: "Desk Lamp",
    imageUrl: "https://example.com/desk_lamp.jpg",
    minWatts: 10,
    maxWatts: 60,
    step: 5,
  },
  {
    name: "Table Fan",
    imageUrl: "https://example.com/table_fan.jpg",
    minWatts: 20,
    maxWatts: 100,
    step: 5,
  },
  {
    name: "Air Purifier",
    imageUrl: "https://example.com/air_purifier.jpg",
    minWatts: 20,
    maxWatts: 100,
    step: 5,
  },
  {
    name: "Heated Blanket",
    imageUrl: "https://example.com/heated_blanket.jpg",
    minWatts: 50,
    maxWatts: 200,
    step: 10,
  },
  {
    name: "Electric Blanket",
    imageUrl: "https://example.com/electric_blanket.jpg",
    minWatts: 50,
    maxWatts: 200,
    step: 10,
  },
  {
    name: "Food Processor",
    imageUrl: "https://example.com/food_processor.jpg",
    minWatts: 200,
    maxWatts: 1000,
    step: 50,
  },
  {
    name: "Rice Cooker",
    imageUrl: "https://example.com/rice_cooker.jpg",
    minWatts: 300,
    maxWatts: 1000,
    step: 50,
  },
  {
    name: "Juicer",
    imageUrl: "https://example.com/juicer.jpg",
    minWatts: 300,
    maxWatts: 800,
    step: 50,
  },
  {
    name: "Hand Mixer",
    imageUrl: "https://example.com/hand_mixer.jpg",
    minWatts: 100,
    maxWatts: 400,
    step: 25,
  },
  {
    name: "Electric Shaver",
    imageUrl: "https://example.com/electric_shaver.jpg",
    minWatts: 5,
    maxWatts: 20,
    step: 1,
  },
  {
    name: "Electric Toothbrush Charger",
    imageUrl: "https://example.com/electric_toothbrush_charger.jpg",
    minWatts: 1,
    maxWatts: 5,
    step: 1,
  },
  {
    name: "Electric Scooter Charger",
    imageUrl: "https://example.com/electric_scooter_charger.jpg",
    minWatts: 50,
    maxWatts: 300,
    step: 10,
  },
  {
    name: "Electric Bicycle Charger",
    imageUrl: "https://example.com/electric_bicycle_charger.jpg",
    minWatts: 50,
    maxWatts: 300,
    step: 10,
  },
  {
    name: "Electric Skateboard Charger",
    imageUrl: "https://example.com/electric_skateboard_charger.jpg",
    minWatts: 50,
    maxWatts: 300,
    step: 10,
  },
  {
    name: "Gaming Console Charger",
    imageUrl: "https://example.com/gaming_console_charger.jpg",
    minWatts: 50,
    maxWatts: 150,
    step: 10,
  },
  {
    name: "Digital Camera Charger",
    imageUrl: "https://example.com/digital_camera_charger.jpg",
    minWatts: 5,
    maxWatts: 20,
    step: 1,
  },
  {
    name: "Portable Speaker Charger",
    imageUrl: "https://example.com/portable_speaker_charger.jpg",
    minWatts: 5,
    maxWatts: 20,
    step: 1,
  },
  {
    name: "Smartwatch Charger",
    imageUrl: "https://example.com/smartwatch_charger.jpg",
    minWatts: 1,
    maxWatts: 10,
    step: 1,
  },
  {
    name: "Headphone Charger",
    imageUrl: "https://example.com/headphone_charger.jpg",
    minWatts: 1,
    maxWatts: 5,
    step: 1,
  },
  {
    name: "Electric Guitar Amplifier",
    imageUrl: "https://example.com/electric_guitar_amplifier.jpg",
    minWatts: 20,
    maxWatts: 200,
    step: 10,
  },
  {
    name: "Electric Bass Amplifier",
    imageUrl: "https://example.com/electric_bass_amplifier.jpg",
    minWatts: 20,
    maxWatts: 200,
    step: 10,
  },
  {
    name: "Home Theater System",
    imageUrl: "https://example.com/home_theater_system.jpg",
    minWatts: 100,
    maxWatts: 500,
    step: 20,
  },
  {
    name: "Projector",
    imageUrl: "https://example.com/projector.jpg",
    minWatts: 100,
    maxWatts: 500,
    step: 20,
  },
  {
    name: "Gaming PC",
    imageUrl: "https://example.com/gaming_pc.jpg",
    minWatts: 300,
    maxWatts: 1000,
    step: 50,
  },
  {
    name: "Electric Skateboard",
    imageUrl: "https://example.com/electric_skateboard.jpg",
    minWatts: 300,
    maxWatts: 1000,
    step: 50,
  },
  {
    name: "Hoverboard",
    imageUrl: "https://example.com/hoverboard.jpg",
    minWatts: 300,
    maxWatts: 1000,
    step: 50,
  },
  {
    name: "Electric Wheelchair",
    imageUrl: "https://example.com/electric_wheelchair.jpg",
    minWatts: 200,
    maxWatts: 500,
    step: 20,
  },
  {
    name: "Electric Scooter",
    imageUrl: "https://example.com/electric_scooter.jpg",
    minWatts: 200,
    maxWatts: 500,
    step: 20,
  },
  {
    name: "Electric Bike",
    imageUrl: "https://example.com/electric_bike.jpg",
    minWatts: 200,
    maxWatts: 500,
    step: 20,
  },
  {
    name: "Electric Lawn Mower",
    imageUrl: "https://example.com/electric_lawn_mower.jpg",
    minWatts: 500,
    maxWatts: 1500,
    step: 50,
  },
];

export default ComponentData;
